version: "2.3"
services:
    embeddings:
        build: .
        ipc: host
        #command: "python3 embeddings.py 30"
        volumes:
            - .:/develop/
        command: "tail -F /dev/null"
        environment:
            - DBCONNECT
